apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    fint.stack: profilbilder
    fint.role: adapter
  name: profilbilder
spec:
  azureFile:
    shareName: profilbilder
    secretName: fintdockervolumes
    secretNamespace: default
    readOnly: false
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=1000
    - gid=1000
