security:
 basic:
  enabled: false

fint:
 adapter:
  organizations: mock.no
  sse-endpoint: http://localhost:8081/provider/sse/%s
  status-endpoint: http://localhost:8081/provider/status
  response-endpoint: http://localhost:8081/provider/response
  avatar:
   basedir: /Users/noasgnil/Documents/Git/fake-avatar-adapter/images
   root: http://10.0.75.1:8091

 oauth:
  enabled: false
